-- AlterTable
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "autoSyncEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "autoSyncInterval" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "lastOrderAutoSyncAt" TIMESTAMP(3);
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "lastProductAutoSyncAt" TIMESTAMP(3);
